### PR TITLE
FIX correctly redirect after successful log in

### LINKED ISSUE #250: User is not sent to their desired destination after registering or verifying with MFA
## Background:

- I am a user with admin rights to the CMS
- I do not have MFA enabled on my account
- MFA is installed on the site (optional or required, it does not matter)

## Reproduction

- I log in to the `/admin`
- I am requested to register an MFA method
- I register an MFA method
- I click the complete button after registering an MFA method

**Expected**: I am logged into the CMS

**Actual**: I am seeing "You're logged in as `username here`"

## Reproduction (alternate)

Given: I have completed the above.

- I log in to the `/admin`
- I am requested to verify with my default MFA method
- I complete this verification

**Expected**: I am logged into the CMS

**Actual**: I am seeing "You're logged in as `username here`"

Possibly a regression since the fix of #223

### PR DESCRIPTION
**Pull request by NightJar**
The usage of the BackURL key in the request does not work with MFA as it operates over many reqeusts, interrupting the 'normal' operation (default member authenticator logic).
MFA gets around this by storing the BackURL value in the session tied to the request - but this was being (correctly) cleared before the redirect is performed after a successful log in.
This commit fixes this by making a short lived store in memory for this value, and is still able to be utilised by the redirect logic from the 'normal' operation.

Resolves #250

### CODE REVIEW

**Comment by NightJar** [comment]
I don't know how to test this :/
There are too many moving parts when it comes to the BackURL - I can't mock the parent class that is used to call `getBackURL` - and to correctly test this logic it requires the `redirectAfterSuccessfulLogin` method to be called first, in order to clear the session and store the URL in the member field for the class.

I opted for the path of least resistance and just made the PR, if anyone has suggestions I'm happy to learn some tricks :)

**Comment by brynwhyman** [comment]
Given that this bug effectively blocks users from logging in, I'm VERY keen to see/help this PR be tested before it's merged. Log in redirects have been causing a number of issues and regressions recently so it's worth the effort reviewing and testing thoroughly before merge.

**Comment by ScopeyNZ** [comment]
I've pushed a commit with the fix I recommend. I've tested #212 with this too. I'll work on putting some functional tests in now.

**Comment by NightJar** [comment]
You have basically rewritten this @ScopeyNZ - is it ready now?

File: src/Authenticator/LoginHandler.php [hunk 1]
```diff
@@ -512,7 +515,9 @@ public function getLogger(): ?LoggerInterface
     }
 
     /**
-     * Adds another option for the back URL to be returned from a current MFA session store
+     * Adds more options for the back URL - to be returned from a current MFA session store or from memory during this
+     * request. The latter is required as session store is cleared before the 'BackURL' key is utilised
```
Comment (NightJar) [inline src/Authenticator/LoginHandler.php]: This docblock needs updating since you've removed the functionality it applies @ScopeyNZ :)

File: src/Authenticator/LoginHandler.php [hunk 2]
```diff
@@ -457,6 +457,9 @@ public function redirectAfterSuccessfulLogin(): HTTPResponse
             return $this->redirect($this->getBackURL() ?: $loginUrl);
         }
 
+        // Redirecting after successful login expects a getVar to be set, store it before clearing the session data
+        $request['BackURL'] = $this->getBackURL();
```
Comment (NightJar) [inline src/Authenticator/LoginHandler.php]: Do you think a comment might be neat for people that are confused about array access on objects?

File: tests/php/Authenticator/LoginHandlerTest.php [hunk 3]
```diff
@@ -232,24 +233,77 @@ public function cannotSkipMFAProvider()
...
+     * @dataProvider skipRegistrationProvider
+     */
+    public function testSkipRegistration($memberFixture, $mfaRequiredInGrace = false, $expectedRedirect = null)
     {
-        $this->setSiteConfig(['MFARequired' => false]);
+        if ($mfaRequiredInGrace) {
+            $this->setSiteConfig([
+                'MFARequired' => true,
+                'MFAGracePeriodExpires' => DBDatetime::now()
+                    ->setValue(strtotime('+1 day', DBDatetime::now()->getTimestamp()))->getTimestamp()
```
Comment (Cheddam) [inline tests/php/Authenticator/LoginHandlerTest.php]: I think we prefer using `->Rfc2822()` in place of `->getTimestamp()` when setting DBDateTime values?

Comment (ScopeyNZ) [reply tests/php/Authenticator/LoginHandlerTest.php]: Thanks

File: src/Authenticator/LoginHandler.php [hunk 4]
```diff
@@ -457,6 +457,10 @@ public function redirectAfterSuccessfulLogin(): HTTPResponse
             return $this->redirect($this->getBackURL() ?: $loginUrl);
         }
 
+        // Redirecting after successful login expects a getVar to be set, store it before clearing the session data
+        /** @see HTTPRequest::offsetSet */
+        $request['BackURL'] = $this->getBackURL();
```
Comment (robbieaverill) [inline src/Authenticator/LoginHandler.php]: lol at this not being defined in SS3

File: tests/php/Authenticator/LoginHandlerTest.php [hunk 5]
```diff
@@ -232,24 +233,77 @@ public function cannotSkipMFAProvider()
         ];
     }
 
-    public function testSkipRegistration()
+    /**
+     * @param $memberFixture
+     * @param $expectedRedirect
```
Comment (robbieaverill) [inline tests/php/Authenticator/LoginHandlerTest.php]: Please add some types

File: src/Authenticator/LoginHandler.php (hunk 4 above)
Comment (NightJar) [reply src/Authenticator/LoginHandler.php]: I'm confused; this PR is for SS4.
Is there something we need to be aware of for the SS3 backport?

Comment (robbieaverill) [reply src/Authenticator/LoginHandler.php]: No, just that offsetSet has no logic in it in SS3. As you were
