### PR TITLE
FIX ensure RegisteredMFAFieldList always has a Member and never "not a Member"

### LINKED ISSUE #221: Text sizing and padding
##### Example
photo_2019-06-25_10-04-06
- [ ] Reduce H1 to 16px equivalent
- [ ] Reduce spacing between H1 and H2 to 8px equivalent
- [x] ~Increase paragraphs from 13px to 14px to improve legibility~
- [x] ~Increase subheading to 14px~

##### Example
photo_2019-06-25_10-04-17
- [ ] Add spacing between MFA options to 16px equivalent
- [ ] Add spacing to bottom of MFA graphic to 16px equivalent
- [ ] Add spacing after MFA options to 16px equivalent

### PR DESCRIPTION
**Pull request by NightJar**
It was found that upon submission of a Member form in the CMS (e.g. to update a password)
there was a 500 server error being returned. The submission is of course attempting to
populate all the form fields with submitted data - the React form field for MFA management
is not a form field in the "accepts user input" sense, it is an interactive component
designed to perform actions directly - thus it has no value. No value means the PHP side
FormField instance is attempted to have `null` set as the value upon submission, which
disagrees strongly with the type hint of `Member`, and caused issues.

As this form field has two valid states - on where editing is possible and the member object
is always equal to `Security::getCurrentUser`, and a read only mode where the member may be any
valid member from the database - which means that simply relying on `Security::getCurrentUser`
would be unreliable, we must both require a member to always be set (via the constructor) and
not accept invalid `setValue` requests - but we cannot throw an exception here because this is
expected behaviour upon a form submission.

Resolves #221

### CODE REVIEW

File: src/FormField/RegisteredMFAMethodListField.php [hunk 1]
```diff
@@ -2,17 +2,41 @@
...
+use SilverStripe\Security\Member;
 use SilverStripe\Security\Security;
 
 class RegisteredMFAMethodListField extends FormField
 {
+    public function __construct($name, $title = null, $value = null) {
+        // Because {@see setValue()} can do nothing on e.g. form submission, it is of critical importance that this
+        // object is never in existence without a valid Member set as the value - however as this is a subclass we
+        // cannot alter the constructor function signature to require the parameter.
+        if (!$value instanceOf Member) {
```
Comment (robbieaverill) [inline src/FormField/RegisteredMFAMethodListField.php]:
```suggestion
        if (!$value instanceof Member) {
```

File: src/FormField/RegisteredMFAMethodListField.php [hunk 2]
```diff
@@ -2,17 +2,41 @@
...
 use SilverStripe\MFA\Service\SchemaGenerator;
+use SilverStripe\Security\Member;
 use SilverStripe\Security\Security;
 
 class RegisteredMFAMethodListField extends FormField
 {
+    public function __construct($name, $title = null, $value = null) {
+        // Because {@see setValue()} can do nothing on e.g. form submission, it is of critical importance that this
+        // object is never in existence without a valid Member set as the value - however as this is a subclass we
+        // cannot alter the constructor function signature to require the parameter.
```
Comment (robbieaverill) [inline src/FormField/RegisteredMFAMethodListField.php]: This isn't true, constructors aren't bound by the same signature in hierarchy like other PHP methods are

File: src/FormField/RegisteredMFAMethodListField.php [hunk 3]
```diff
@@ -2,17 +2,41 @@
...
+        return parent::__construct($name, $title, $value);
+    }
+
+    public function setValue($value, $data = null) {
+        // When a form submits, it populates data from POST values.
+        // This field is not really a form field - it is a React JS component that renders interactive controls
+        // for a member to manage their MFA settings. It therefore does not have a value, and `null` is not a valid
+        // instance of Member - this causes a PHP Emeregency error (resulting in a HTTP 500). To this end, only ever
+        // set the value if the value passed in is an instance of Member.
+        if ($value instanceOf Member) {
```
Comment (robbieaverill) [inline src/FormField/RegisteredMFAMethodListField.php]:
```suggestion
        if ($value instanceof Member) {
```

File: src/FormField/RegisteredMFAMethodListField.php (hunk 2 above)
Comment (NightJar) [reply src/FormField/RegisteredMFAMethodListField.php]: Oh 😓

File: src/FormField/RegisteredMFAMethodListField.php [hunk 4]
```diff
@@ -2,17 +2,43 @@
...
 class RegisteredMFAMethodListField extends FormField
 {
+    public function __construct($name, $title, $value)
+    {
+        // Because {@see setValue()} can do nothing on e.g. form submission, it is of critical importance that this
+        // object is never in existence without a valid Member set as the value - we have set the `$value` parameter as
+        // required, however we still need to ensure that it is a valid value.
+        if (!$value instanceof Member) {
+            throw new InvalidArgumentException(__CLASS__ . ' requires a Member to be set at all times');
+        }
```
Comment (robbieaverill) [inline src/FormField/RegisteredMFAMethodListField.php]: My suggestion would be to move this to constructor arg type hints, then you'll get a runtime exception instead:

```php
public function __construct(string $name, string $title, Member $value)
```

Comment (NightJar) [reply src/FormField/RegisteredMFAMethodListField.php]: And that's still legit?
Golly!

**Comment by NightJar** [comment]
Rebased to 4.0, with typehint adjustments

File: composer.json [hunk 5]
```diff
@@ -38,6 +38,9 @@
         "squizlabs/php_codesniffer": "^3.0"
     },
     "extra": {
+        "branch-alias": {
+            "dev-master": "4.x-dev"
+        },
```
Comment (robbieaverill) [inline composer.json]: Need to rebase this commit out

File: src/FormField/RegisteredMFAMethodListField.php [hunk 6]
```diff
@@ -2,17 +2,43 @@
...
+use SilverStripe\Security\Member;
 use SilverStripe\Security\Security;
 
 class RegisteredMFAMethodListField extends FormField
 {
+    /**
+     * Because {@see setValue()} can do nothing on e.g. form submission, it is of critical importance that this
+     * object is never in existence without a valid Member set as the value - we have set the `$value` parameter as
+     * required, however we still need to ensure that it is a valid value. We do this via type hints, and removing the
+     * optionality of the parameters for this constructor - excepting that one can still pass `null` for the $title.
```
Comment (robbieaverill) [inline src/FormField/RegisteredMFAMethodListField.php]: I don't think the last sentence needs to be there to be honest, the signature essentially says this already

File: composer.json (hunk 5 above)
Comment (NightJar) [reply composer.json]: I already did 🤔

**Comment by robbieaverill** [comment]
I assume the issue reference should actually be #211?
