### PR TITLE
Backport EnforcementManager fixes to 3.0

### LINKED ISSUE #369: New user in group with limited permissions cannot login
Scenario
- MFA is required i.e. non-optional
- Newly setup user.
- Member is assigned to a single group. 
- That group that has the following permissions:
  1. Access a custom ModelAdmin
  2. Access the files section

When attempting to access the CMS, user is prompted to enter username/password, get redirect back to that enter credentials screen with empty username/password fields.  Never get prompted to setup MFA. URL is:
/Security/login?BackURL=%2Fadmin%2Fpages%2F 

If use a different browser and instead of going to /admin go to /admin/mymodeladmin or /admin/files, then experience is exactly the same, however the ?BackURL equals %2Fadmin%2Fmymodeladmin%2F

If I also add the default "Content Author" group to the new user, then they can login to /admin and setup MFA

### Pull requests
- [x] SS4: https://github.com/silverstripe/silverstripe-mfa/pull/375
- [x] SS3: https://github.com/silverstripe/silverstripe-mfa/pull/382

### LINKED ISSUE #376: (CMS3) Users with no CMS access can't authenticate when MFA is mandatory
#### Affects

~MFA 4.0.x~, 3.0.x

#### Description

Following on from #369, we've received and corroborated a report that Members with no CMS access are barred from completing login when MFA is configured to be mandatory. This is due to a discrepancy in behaviour between the methods used to determine whether a user can bypass MFA at different stages of the login process:

- When determining whether to prompt for MFA, [`EnforcementManager::shouldRedirectToMFA()`](https://github.com/silverstripe/silverstripe-mfa/blob/fb7849fb752a229a4b2968c04b88651c6fccfe89/src/Service/EnforcementManager.php#L95) is called, which determines whether the user has access to the CMS and returns `false`, allowing login to proceed.
- Later, after login has completed, [`MFA\MemberAuthenticator\LoginHandler::redirectAfterSuccessfulLogin()`](https://github.com/silverstripe/silverstripe-mfa/blob/fb7849fb752a229a4b2968c04b88651c6fccfe89/src/Authenticator/LoginHandler.php#L432) calls [`EnforcementManager::canSkipMFA()`](https://github.com/silverstripe/silverstripe-mfa/blob/fb7849fb752a229a4b2968c04b88651c6fccfe89/src/Service/EnforcementManager.php#L63), which _does not_ check whether the user has access to the CMS and therefore returns `false`, causing an immediate logout and redirect to the authentication screen.

#### Replication

- Create test Member with no CMS permissions
- Set MFA to be mandatory in Settings
- Attempt to log in as test Member, observe immediate redirect back to login

#### PRs

- [x] 4.0 branch: #379 
- [x] 3.0 branch: #382

### LINKED ISSUE #380: Cannot login locally when MFAEnabled in SiteConfig, even when config enabled = false
Issue
I cannot login to /admin on my dev enviornment if MFAEnabled in the databse is on, even if config enabled is off.

Steps to reproduce:
1. Download a snapshot of the database from Prod with SiteCofnig MFAEnabled true. (or just change manually in your DB)
2. Go to /admin on local and you will be redirected to the login form
3. Submit as usual, 
4. You will be redirected back to the login form

It seems that the login form just redirects to itself if it finds that MFA is disabled. I think because it calls `redirectAfterSuccessfulLogin` on the MFA authenticator class, not its parent class, even when MFA is disabled.

Im getting this in a fresh install of CWP Recipe 2.5

### PR DESCRIPTION
**Pull request by Cheddam**
This PR backport 3 recent patches to the 3.0 line:

- Resolves #369
- Resolves #376
- Resolves #380

### CODE REVIEW

File: src/Service/EnforcementManager.php [hunk 1]
```diff
@@ -46,44 +49,50 @@ class EnforcementManager extends SS_Object
...
      * @return bool
      */
     public function canSkipMFA(Member $member): bool
     {
+        if (!$this->isEnabled()) {
+            return true;
+        }
+
+        if ($this->config()->get('requires_admin_access') && !$this->hasAdminAccess($member)) {
+            return true;
```
Comment (emteknetnz) [inline src/Service/EnforcementManager.php:72]: seems like this should return false?  am i reading this wrong?

if it should return true, then need some comments explaining why its ok to skip mfa when admin access is required though the member doesn't have it

File: src/Service/EnforcementManager.php [hunk 2]
```diff
@@ -209,42 +210,67 @@ public function isGracePeriodInEffect(): bool
...
+                    && $candidate->MenuItem->controller
+                    && singleton($candidate->MenuItem->controller)->canView($member)
+                ) {
+                    return true;
+                }
+            }
+
+            return false;
+        } finally {
+            Session::set('loggedInAs', $currentMemberID);
```
Comment (emteknetnz) [inline src/Service/EnforcementManager.php:251]: this finally block won't get reached because the function will get existed by either of the two return statements above it

File: src/Service/EnforcementManager.php (hunk 1 above)
Comment (Cheddam) [reply src/Service/EnforcementManager.php:72]: It's a bit of a confusing situation - the point is that admin access is required to _use_ MFA by default, as there's no built-in way for a user to manage their MFA configuration outside the admin UI. Therefore, users that _don't_ have admin access can skip anything MFA-related (unless configured otherwise.)

File: src/Service/EnforcementManager.php (hunk 2 above)
Comment (Cheddam) [reply src/Service/EnforcementManager.php:251]: `finally` statements always fire, even if a `return` statement is hit in the `try` block: https://www.php.net/manual/en/language.exceptions.php#language.exceptions.finally

File: src/Service/EnforcementManager.php (hunk 1 above)
Comment (emteknetnz) [reply src/Service/EnforcementManager.php:72]: could you put in a comment explaining this

**Comment by emteknetnz** [comment]
I was unable to replicate the original issue on my local, possibly I did something wrong at my end

Please note I was using the main branch tagged at 3.0.0, not the pull-request

Possible a different issue where mandatory MFA is not being enforced properly

```
~/Sites/ss3base $ composer info | grep silverstripe
silverstripe-themes/simple         3.1.1    The SilverStripe simple theme (default SilverStripe 3 theme)
silverstripe/cms                   3.7.3    The SilverStripe Content Management System
silverstripe/framework             3.7.4    The SilverStripe framework
silverstripe/login-forms           3.0.0    A collection of templates for the CMS login screens
silverstripe/mfa                   3.0.0    Enable multi-factor authentication with fallback codes
silverstripe/reports               3.7.3    Reports module for SilverStripe CMS
silverstripe/security-extensions   3.0.0    A temporary polyfill repository for security improvements that will be ported into ...
silverstripe/siteconfig            3.7.3    Site wide settings administration.
silverstripe/totp-authenticator    3.0.0    A TOTP authenticator for use with silverstripe/mfa
```

_ss_environment.php
define('SS_MFA_SECRET_KEY', 'abcdef12345');

Site Settings > MFA is required for everyone
MFA will be required from (optional) = [Blank]

Created Group "MyGroup" with permissions "Access to 'Files' section"

Create test user "test@test.com" added to "MyGroup"

In a different browser, logged in with the user

Was not prompted to setup MFA, instead went into CMS and saw ModelAdmins "Files" and "Help"

**Comment by Cheddam** [comment]
@emteknetnz I can replicate the behaviour you're seeing, but I also just re-tested this set of instructions against the PR, and I get the expected behaviour (the user is redirected to configure MFA.)

I don't think it's super important that all of the original issues can be replicated _without_ these commits in place - rather, we need to make sure that issues aren't present _with_ them in place.

**Review by robbieaverill — APPROVED** [review]
LGTM. I assume the logic was peer reviewed in the 4.0 branch and this is a backport so haven't looked too closely.

**Comment by emteknetnz** [comment]
Tested this against original redirection loop issue, it fixes it

Confirmed that:
- Setting MFA required will function as you would expect
- MFA optional still functions correctly (ie if you setup MFA here it works)
- MFA required with grace period still functions correctly

Will merge shortly

**Comment by brynwhyman** [comment]
Fancy a patch release for `3.0` @emteknetnz ? :)

**Comment by emteknetnz** [comment]
@brynwhyman https://github.com/silverstripe/silverstripe-mfa/releases/tag/3.0.1
