### PR TITLE
FIX do not allow last method removal when MFA is required

### LINKED ISSUE #207: CMS users doesn't get notified why they can't remove their last method when MFA is enforced
In the event that MFA is enforced and only one method is registered by the user, the user does not get any notification why they can't remove their last method in their profile, when pressing the "remove" link under their registered MFA method.

**Solution** 
- Remove the 'Remove method' button if MFA is enforced and there is only one registered method for the member.

~Consider using toast notification OR Banner Alert with text:
"Unable to remove this method, as MFA is required for login"~

### PR DESCRIPTION
**Pull request by NightJar**
Although MFA was required on a site it was still possible for a member to adjust their MFA settings to remove all methods, and effecitvely maintain a state of not having MFA. Now if MFA is required it is no longer possible to remove the last (non-backup) method on a member account.

Resolves #207

### CODE REVIEW

File: src/Service/RegisteredMethodManager.php [hunk 1]
```diff
@@ -104,6 +105,33 @@ public function registerForMember(Member $member, MethodInterface $method, $data
...
+     * @return bool
+     */
+    public function canRemoveMethod(Member $member, MethodInterface $method): bool
+    {
+        $removable = true;
+        $remainingMethods = $member->RegisteredMFAMethods()->count();
+        $mfaIsRequired = Injector::inst()->get(EnforcementManager::class)->isMFARequired();
+
+        // This is the last method (besides the backup method), and MFA is required
+        if ($mfaIsRequired && $remainingMethods === 2) {
```
Comment (ScopeyNZ) [inline src/Service/RegisteredMethodManager.php]: There is a possibility (with configuration) that you don't have a backup method - this means this check is wrong. You need to assert that they have a backup method registered before checking `2` - otherwise it'll be just `1`.

File: src/Service/RegisteredMethodManager.php [hunk 2]
```diff
@@ -104,6 +105,33 @@ public function registerForMember(Member $member, MethodInterface $method, $data
...
+     * By default this is false if MFA is required and the method is the last on the Member (besides the backup method)
+     * but the funcation provides a hook point for extensibility e.g. if an site requires a particular method to be in
+     * use by a subset of members - admins must use U2F but normal users can use TOTP.
+     *
+     * @param Member $member
+     * @param MethodInterface $method
+     * @return bool
+     */
+    public function canRemoveMethod(Member $member, MethodInterface $method): bool
+    {
```
Comment (ScopeyNZ) [inline src/Service/RegisteredMethodManager.php]: I feel like this is better suited as an exception (maybe as `assertCanRemoveMethod`). The UI should prevent getting here and an exception can provide more context (like the fact it should be a `403`). Keen to hear thoughts.

Comment (NightJar) [reply src/Service/RegisteredMethodManager.php]: I feel like this would be unnecessary. The method could be used in other contexts than mid-removal, such as whether or not to show an action to remove - not just in the middle of a removal request. In the case that it would throw and exception would introduce a try-catch statement, and/or having to deal with an HTTP error for what should essentially be a boolean.
