### PR TITLE
NEW Adding logic to handle a MFA method marked as a backup method & fixing flows

### LINKED ISSUE #28: Registration is complete - frontend
The final screen of the MFA app when registering a new MFA method.

Designs: https://projects.invisionapp.com/share/3PNSKZQYBJZ#/screens/321189809

ACs
- Screen is built in React app
- Screen is presented after clicking the `Finish` action in [this design](https://projects.invisionapp.com/share/3PNSKZQYBJZ#/screens/322766388), implemented in #13
- Button just says "Continue"

### LINKED ISSUE #31: Logic to make backup codes a 'back-up' method
A back-up method should:

- Be a mandatory set-up process after you have set up at least one other MFA method
- Should never be presented as the default MFA method

It might make sense to ensure that you are logged in after seeing registering backup codes while doing this task. Currently you aren't in a logged in state and have to use the MFA method you just set up.

### PR DESCRIPTION
**Pull request by ScopeyNZ**
- There is now a configuration option for a "backup method"
 - Back-up codes (aka "recovery codes") are the bundled default
 - A back-up method is a mandatory registration that appears after setting up at least one other method
 - This method will not be picked as the default method when logging in
- Added JS components for the "BasicMath" test method. This could be removed in the future
- Updated the flow for registration - ensuring that you don't have to login immediately after registering MFA for the first time
- Added a confirmation screen when you complete the MFA registration flow
- Added some checks to ensure a malicious user cannot circumvent MFA by choosing a custom flow

Fixes #31 
Fixes #28

### CODE REVIEW

File: client/src/components/Register.js [hunk 1]
```diff
@@ -4,17 +4,44 @@ import React, { Component } from 'react';
...
+
+    // Set initial selected method value based on props...
+    let selectedMethod = null;
+
+    // Set the backup method as the "selected" method if there are methods already registered for
+    // the user but one of those isn't the backup method.
+    if (
+      registeredMethods
+      && registeredMethods.length
+      && !registeredMethods.find(method => method.urlSegment === backupMethod.urlSegment)
```
Comment (robbieaverill) [inline client/src/components/Register.js]: As discussed on slack, perhaps you could add `.length` to avoid any ambiguity around the comparison and the length check

File: client/src/components/Register.js [hunk 2]
```diff
@@ -86,13 +129,66 @@ class Register extends Component {
...
+
+    window.location = complete;
+  }
+
+  /**
+   * Render a confirmation screen to inform the user that set up has been completed
+   *
+   * @return {HTMLElement}
+   */
+  renderCompleteScreen() {
```
Comment (robbieaverill) [inline client/src/components/Register.js]: Can we have this in its own component please?

File: client/src/components/Register.scss [hunk 3]
```diff
@@ -0,0 +1,18 @@
+.mfa-register-confirmation {
+  text-align: center;
+  margin: 3em auto 3em;
+
+  &__icon {
+    line-height: 1;
+    color: $color-green;
+    font-size: 76px;
```
Comment (robbieaverill) [inline client/src/components/Register.scss]: There's a couple of spots where variables could be used here

File: client/src/containers/MultiFactorApp.js [hunk 4]
```diff
@@ -9,12 +9,17 @@ import LoadingIndicator from 'components/LoadingIndicator';
...
 class MultiFactorApp extends Component {
   constructor(props) {
+    const { ss: { i18n } } = window;
+
     super(props);
     this.state = {
+      loginCompleted: false,
       schema: null,
       schemaLoaded: false,
+      title: i18n._t('MFA.TITLE', 'Multi-factor authentication'),
```
Comment (robbieaverill) [inline client/src/containers/MultiFactorApp.js]: `MultiFactorApp` maybe might be better. `MFA` is unlikely to have global collisions but you never know, it's only three letters.

File: client/src/containers/MultiFactorApp.js [hunk 5]
```diff
@@ -60,12 +88,21 @@ class MultiFactorApp extends Component {
...
-    if (!registeredMethods.length) {
-      return <Register {...schema} />;
-    }
-
-    return <Login {...schema} onCompleteLogin={this.handleCompleteLogin} />;
+    return (
+      <div>
+        {title && <h1>{title}</h1>}
+        {showRegister && <Register {...schema} onSetTitle={this.handleSetTitle} />}
+        {showRegister || (
```
Comment (robbieaverill) [inline client/src/containers/MultiFactorApp.js]: I think this might be tidier if it were written like this:

```jsx
return (
  <div>
    { ... }
    { this.renderRegister() }
    { this.renderLogin() }
  </div>
);
```

Then you can put the logic for whether to render anything at the top of those methods.

Thoughts?

File: src/Authenticator/LoginHandler.php [hunk 6]
```diff
@@ -147,16 +158,21 @@ public function startRegistration(HTTPRequest $request)
...
         }
 
+        $method = $this->getMethodRegistry()->getMethodByURLSegment($request->param('Method'));
+
         // If the user isn't fully logged in and they already have a registered method, they can't register another
-        if (is_null($loggedInMember) && $sessionMember && count($sessionMember->RegisteredMFAMethods()) > 0) {
+        // provided that they're not registering a backup method
+        $registeredMethodCount = $sessionMember->RegisteredMFAMethods()->count();
+        $isRegisteringBackupMethod =
+            get_class($method) === Config::inst()->get(MethodRegistry::class, 'default_backup_method');
```
Comment (robbieaverill) [inline src/Authenticator/LoginHandler.php]: This won't be extensible - perhaps you could do `is_a($method, MethodRegistry::config()->get('default_backup_method'), true)` which would allow subclasses too

File: client/src/components/Register.js (hunk 1 above)
Comment (ScopeyNZ) [reply client/src/components/Register.js]: Yeah perhaps making it clear there's no registered method with `registeredMethods.filter(isABackupMethod).length === 0` is nicer

Comment (ScopeyNZ) [reply client/src/components/Register.js]: I've updated that bit now :)

File: src/Service/EnforcementManager.php [hunk 7]
```diff
@@ -73,6 +74,28 @@ public function shouldRedirectToMFA(Member $member)
...
 
+    /**
+     * Check if the provided member has registered the required MFA methods. This includes a "back-up" method set in
+     * configuration plus at least one other method.
+     * Note that this method returns true if there is no backup method registered (and they have one other method
+     *
+     * @param Member&MemberExtension $member
+     * @return bool
+     */
+    public function hasFullyRegisteredMFA(Member $member)
```
Comment (robbieaverill) [inline src/Service/EnforcementManager.php]: The method name irks me a little. How would you feel about `hasCompletedMFARegistration()` instead?

File: _config/backupcodes.yml [hunk 8]
```diff
@@ -4,3 +4,8 @@ name: MFABackupCodeAuthenticator
 SilverStripe\MFA\Service\MethodRegistry:
   methods:
     backupCodes: SilverStripe\MFA\BackupCode\Method
+---
+name: MFADefaultBackupMethod
+---
+SilverStripe\MFA\Service\MethodRegistry:
+  default_backup_method: SilverStripe\MFA\BackupCode\Method
```
Comment (robbieaverill) [inline _config/backupcodes.yml]: Just keep this in PHP I reckon

File: src/Service/MethodRegistry.php [hunk 9]
```diff
@@ -24,6 +24,17 @@ class MethodRegistry
...
+    /**
+     * A string referring to the classname of the method (implementing SilverStripe\MFA\Method\MethodInterface) that is
+     * to be used as the back-up method for MFA. This alters the registration of this method to be required - a forced
+     * registration once the user has registered at least one other method. Additionally it cannot be set as the default
+     * method for a user to log in with.
+     *
+     * @config
+     * @var string
+     */
+    private static $default_backup_method;
```
Comment (robbieaverill) [inline src/Service/MethodRegistry.php]: Suggestion to put the default here instead of in the YAML

File: src/Service/SchemaGenerator.php [hunk 10]
```diff
@@ -38,7 +41,9 @@ public function getSchema(Member $member)
             'registeredMethods' => $registeredMethods,
             'availableMethods' => $this->getAvailableMethods($exclude),
             'defaultMethod' => $this->getDefaultMethod($member),
+            'backupMethod' => $this->getBackupMethod(),
             'canSkip' => $enforcementManager->canSkipMFA($member),
+            'isFullyRegistered' => $enforcementManager->hasFullyRegisteredMFA($member),
```
Comment (robbieaverill) [inline src/Service/SchemaGenerator.php]: `hasCompletedRegistration` feels better to me (see previous comment)

File: src/Service/SchemaGenerator.php [hunk 11]
```diff
@@ -77,9 +82,12 @@ protected function getAvailableMethods(array $exclude = [])
         // Get all methods enabled on the site
         $allMethods = MethodRegistry::singleton()->getMethods();
 
+        // Get the backup method as we omit this from the "available" methods.
+        $backupMethod = Config::inst()->get(MethodRegistry::class, 'default_backup_method');
+
         // Compile details for methods that aren't already registered to the user
         foreach ($allMethods as $method) {
-            if (in_array($method->getURLSegment(), $exclude)) {
+            if (in_array($method->getURLSegment(), $exclude) || get_class($method) === $backupMethod) {
```
Comment (robbieaverill) [inline src/Service/SchemaGenerator.php]: Same thing here with the `is_a()` instead to handle subclasses. Perhaps a utility function like `->isDefaultBackupMethod($method)` somewhere?

File: client/src/styles/mfa.scss [hunk 12]
```diff
@@ -0,0 +1,39 @@
+body.mfa {
+  .page-header {
+    margin-bottom: 0;
+  }
+
+  // Hide the template provided h1
+  h1 {
```
[the remark this answers is not in the document]
Comment (Cheddam) [reply client/src/styles/mfa.scss]: Thinking more about this, I'd suggest that all the base heading styles shift into Accessway when we build that, and we use classes to override any particular attributes (margins, padding, etc.) that need adjustment on an individual basis within the MFA styling.

File: client/src/components/Register.scss (hunk 3 above)
Comment (ScopeyNZ) [reply client/src/components/Register.scss]: I moved the `margin-bottom` from the title to a variable and style on `mfa.scss`. I'm not sure if there's value in assigning variables to the other bits? Maybe the font-size on the big tick could be used for another screen. The margin stuff here is provided because this screen is pretty unique in it's spacing - I didn't see a screen that had similar spacing.

I'm happy to remove all the special snowflake spacing if you think we should be consistent?

Comment (robbieaverill) [reply client/src/components/Register.scss]: Continual improvement over perfection...

File: client/src/containers/MultiFactorApp.js (hunk 5 above)
Comment (ScopeyNZ) [reply client/src/containers/MultiFactorApp.js]: > Thoughts?
I wish we had `v-if` and `v-else` 😆 . I agree it's kind of ugly. I'm often torn about what's best with putting render conditionals in `renderThing` - mostly because in some cases you want "else" logic. I'll do it though - I agree it's cleaner. 🙂

File: src/Authenticator/LoginHandler.php (hunk 6 above)
Comment (ScopeyNZ) [reply src/Authenticator/LoginHandler.php]: Sure. It'd be pretty weird to have parent/sub-classes on your MFA methods but 🤷‍♂️

File: client/src/styles/mfa.scss [hunk 13]
```diff
@@ -0,0 +1,39 @@
...
+    display: none;
+  }
+
+  // Allow the h1 rendered by the React app to display
+  .mfa__app h1 {
```
[the remark this answers is not in the document]
Comment (ScopeyNZ) [reply client/src/styles/mfa.scss]: Yeah good point

File: client/src/styles/mfa.scss (hunk 12 above)
[the remark this answers is not in the document]
Comment (ScopeyNZ) [reply client/src/styles/mfa.scss]: There's not really any way to hide the `<h1>` except with that selector. If we don't hide it then we'll have to do some hacky DOM manipulation to change the title. We could just leave it "for now" but then we have doubled up titles?

I'm not really sure what else to do but this... Until we have "accessway"

File: src/Service/SchemaGenerator.php (hunk 11 above)
Comment (ScopeyNZ) [reply src/Service/SchemaGenerator.php]: Yep I've added a utility method to `MethodRegistry`.

File: client/src/styles/mfa.scss (hunk 12 above)
[the remark this answers is not in the document]
Comment (Cheddam) [reply client/src/styles/mfa.scss]: I think maybe just ignoring its existence might be better in the short term to be honest - but happy to leave this as-is for now given it'll change again soon anyway.
