### PR TITLE
FIX Adding CSRF to registration and verification flows

### LINKED ISSUE #123: Implement CSRF on "complete" actions
We have `start` and `complete` action for "register" and "verify". We should ensure that CSRF is checked on the `complete` part of these actions.

One major consideration here is that we need to think about how to implement CSRF for the `BackupCode` implementation as backup codes are created (or regenerated) on the `start` action.

### PR DESCRIPTION
**Pull request by ScopeyNZ**
Fixes #123

### CODE REVIEW

File: client/src/components/Verify.js [hunk 1]
```diff
@@ -118,8 +121,9 @@ class Verify extends Component {
    */
   handleCompleteVerification(verifyData) {
     const { endpoints: { verify }, onCompleteVerification } = this.props;
-    const { selectedMethod } = this.state;
-    const endpoint = verify.replace('{urlSegment}', selectedMethod.urlSegment);
+    const { selectedMethod, token } = this.state;
+    const params = token ? `?SecurityID=${token}` : '';
```
Comment (robbieaverill) [inline client/src/components/Verify.js]: You can provide the SecurityID in the post body, doesn't have to be in the query string

Comment (ScopeyNZ) [reply client/src/components/Verify.js]: I _could_ do this. I'll have to (JSON) decode the request on the server-side. Currently the method implementations get to define what the request payload is (in their React components) and then get to decode the request payload themselves (in their `VerifyHandler` implementation).

I decided I wouldn't bother changing that and all the methods to match.

Comment (robbieaverill) [reply client/src/components/Verify.js]: Good justification
